# output paths for hydra logs
run:
  dir: ${base_outdir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${base_outdir}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
# job:
#   env_set:
#     EXAMPLE_VAR: "example_value"
