model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss_epoch" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: -1 # here, save every model. Internally, if used with `run_irreducible.py`, the callback will save the best model, the worst model, some models with intermediate values of irreducible losses
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${work_dir}/src
