# @package _global_
defaults:
  - override /model/large_model: cifar100_resnet.yaml
  - override /datamodule: cifar100_datamodule.yaml
  - override /irreducible_loss_generator: precomputed_loss #note: will need to overwrite checkpoint path on terminal

model:
  percent_train: 0.1

trainer:
  max_epochs: 150
  gpus: 1

datamodule:
  data_dir: "/scratch-ssd/goldiprox/data/"
  batch_size: 320

eval_set: test

logger:
  wandb:
    entity: "mtrazzak"
    project: "cifar100_double_new"