# @package _global_
defaults:
  - override /model/large_model: cifar100_resnet.yaml
  - override /datamodule: cifar100_datamodule.yaml
  - override /irreducible_loss_generator: irreducible_loss_model.yaml

model:
  percent_train: 0.1

trainer:
  max_epochs: 100

datamodule:
  batch_size: 320

logger:
  wandb:
    project: "cifar100_holdout_ablations_final"

seed: 12

irreducible_loss_generator:
  checkpoint_path: null