# @package _global_
# line above ensures that the experiment overrides root settings:
# we need this so our configs affect the global/root config. it has to be the first line in the file
defaults:
  - override /model: importance_sampling_model
  - override /model/model: cifar100_resnet.yaml
  - override /datamodule: cifar100_datamodule.yaml
  - override /logger: wandb
  - override /optimizer: adamw
  - override /datamodule/trainset_corruption: label_noise.yaml 

model:
  percent_train: 0.1

trainer:
  max_epochs: 150
  gpus: 1

datamodule:
  data_dir: "/home/hert6131/data/"
  batch_size: 320
  trainset_data_aug: True
  
eval_set: test

logger:
  wandb:
    project: "cifar100"
    entity: "goldiprox"
    
optimizer:
  lr: 0.001