# @package _global_
defaults:
  - override /model/large_model: cifar_resnet.yaml
  - override /datamodule: cinic10_datamodule.yaml
  - override /irreducible_loss_generator: irreducible_loss_model.yaml
  - override /datamodule/trainset_corruption: label_noise.yaml 

irreducible_loss_generator:
  checkpoint_path: "/auto/users/muhzak/goldi_checkpoints/cinic10_irred_losses.ckpt"

model:
  percent_train: 0.1

trainer:
  max_epochs: 25
  gpus: [1]

datamodule:
  data_dir: "/scratch-ssd/goldiprox/data/"
  batch_size: 320

logger:
  wandb:
    project: "label_noise_1b"
    entity: "goldiprox"