# @package _global_
# line above ensures that the experiment overrides root settings:
# we need this so our configs affect the global/root config. it has to be the first line in the file

defaults:
  - override /model: multi_model
  - override /model/large_model: null
  - override /datamodule: clothing1m_dirty_datamodule
  - override /logger: wandb
  - override /irreducible_loss_generator: precomputed_loss #note: will need to overwrite checkpoint path on terminal
  - override /optimizer: adamw
  - override /selection_method: null # needs to be overriden

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters
# Shared across all models.
seed: 0

trainer:
  gpus: 1
  min_epochs: 50
  max_epochs: 50 #an epoch here is actually 0.1 of an epoch

irreducible_loss_generator:
  f: /auto/users/muhzak/goldi_checkpoints/c1m_dirty_precalc.pt

datamodule:
  batch_size: 320

optimizer:
  lr: 0.001

logger:
  wandb:
    project: "c1m_model_zoo"
    entity: "goldiprox"

eval_set: test

base_outdir: logs
# model/large_model: c1m_zoo_googlenet, c1m_zoo_inception_v3, c1m_zoo_mobilenet_v2, c1m_zoo_resnet34, c1m_zoo_resnet50, c1m_zoo_vgg11_bn