# @package _global_
defaults:
  - override /model/large_model: mnist_mlp512
  - override /datamodule: ambimnist_datamodule.yaml
  - override /irreducible_loss_generator: irreducible_loss_model.yaml

irreducible_loss_generator:
  checkpoint_path: "/auto/users/muhzak/goldi_checkpoints/mnist_noise.ckpt"

model:
  percent_train: 0.1

trainer:
  max_epochs: 10
  gpus: 1
  val_check_interval: 0.2

datamodule:
  data_dir: "/scratch-ssd/goldiprox/data/"
  batch_size: 320
  trainset_data_aug: False
#python3 run.py -m +experiment=mnist_ambi selection_method=reducible_loss_selection,irreducible_loss_selection,cross_entropy_loss_selection trainer.gpus=[0]
#python3 run.py -m +experiment=mnist_ambi selection_method=uniform_selection_with_tracking,gradnorm_ub_selection trainer.gpus=[1]
# python3 run.py -m +experiment=mnist_label_noise selection_method=reducible_loss_selection,irreducible_loss_selection,cross_entropy_loss_selection,uniform_selection_with_tracking,gradnorm_ub_selection +datamodule.pc_corrupted=0.0,0.1,0.2,0.3,0.4 trainer.gpus=[0]
# python3 run.py -m +experiment=mnist_label_noise selection_method=reducible_loss_selection,irreducible_loss_selection,cross_entropy_loss_selection,uniform_selection_with_tracking,gradnorm_ub_selection +datamodule.trainset_corruption.pc_corrupted=0.5,0.6,0.7,0.8,0.9 trainer.gpus=[1]
  
eval_set: test

logger:
  wandb:
    project: "mnist_ambi"
    entity: "goldiprox"
    
optimizer:
  lr: 0.001