# @package hydra.launcher
submitit_folder: $&#123;hydra.sweep.dir/.submitit/%j
timeout_min: 3
gres: gpu:titanrtx:1
cpus_per_task: 10
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
signal_delay_s: 120
max_num_timeout: 0
array_parallelism: 10
num_calls: 0